---
- hosts: bootstrap
  user: root
  vars_files:
    - vars/global.yml
    - vars/cobbler.yml
    - vars/ovirt.yml
    - vars/private.yml
  tasks:
    - include: "{{ path.tasks }}/common.yml"
    - include: "{{ path.tasks }}/centos.yml"
    - include: "{{ path.tasks }}/setup-cobbler.yml"
    - include: "{{ path.tasks }}/cobbler-repos.yml"
  handlers:
    - include: "{{ path.handlers }}"
