#!/usr/bin/env ansible-playbook
---
- hosts: desktops
  user: root
  vars_files:
    - vars/global.yml
    - vars/gluster.yml
    - vars/common.private.yml
  handlers:
  - include: "{{ path.handlers }}"
  tasks:
  - include: "{{ path.tasks }}/common.yml"
  - include: "{{ path.tasks }}/change-user-pass.yml"
  - include: "{{ path.tasks }}/setup-gluster.yml"
  - include: "{{ path.tasks }}/setup-gluster-volumes.yml"
    when: inventory_hostname in groups['gluster']
  - include: "{{ path.tasks }}/configure-network-mounts.yml"
