---
- hosts: bootstrap
  user: root
  vars_files:
    - vars/global.yml
    - vars/idm-client.yml
    - vars/gluster.yml
    - vars/private.yml
  tasks:
    - include: "{{ path.tasks }}/common.yml"
    - include: "{{ path.tasks }}/centos.yml"
    #- include: "{{ path.tasks }}/idm-client.yml"
    #- include: "{{ path.tasks }}/setup-gluster.yml"
  handlers:
    - include: "{{ path.handlers }}"
