---
- hosts: idm
  user: root
  vars_files:
    - vars/global.yml
    - vars/idm.yml
    - vars/idm.private.yml
  vars_prompt:
    - name: ipaserver_admin_password
      prompt: "What should the admin password be for IPA?"
      private: yes
      default: "{{ vault_ipa_admin_password }}"
    - name: ipaserver_dir_admin_password
      prompt: "What should the admin password be for the Directory Server?"
      private: yes
      default: "{{ vault_ipa_dir_admin_password }}"
  tasks:
    - include: "{{ path.tasks }}/common.yml"
    - include: "{{ path.tasks }}/centos.yml"
  roles:
    - ipaserver
  handlers:
  - include: "{{ path.handlers }}"
