---
- hosts: hypervisors
  user: root
  vars_files:
    - vars/global.yml
    - vars/ovirt.yml
  vars_prompt:
    - name: admin_password
      prompt: "What should the admin password be for oVirt Engine?"
      private: yes
  tasks:
  - include: "{{ path.tasks }}/common.yml"
  - include: "{{ path.tasks }}/centos.yml"
  - include: "{{ path.tasks }}/setup-hyp.yml"
  handlers:
  - include: "{{ path.handlers }}"
