---
- authorized_key:
    user: root
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags:
    - common
    - ssh

- yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ global_pkgs_inst }}"
  tags:
    - common
    - packages
