---
- authorized_key:
    user: root
    key: "{{ lookup('file', '~/.ssh/id_ecdsa.pub') }}"
  tags:
    - common
    - ssh

- yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ global_pkgs_inst }}"
  tags:
    - common
    - packages

- name: "Add hosts from inventory to /etc/hosts"
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    state: present
  with_items: "{{ groups['all'] }}"
