---
- name: Ensure necessary software is installed to allow network access
  package:
    name: "{{item}}"
    state: present
  with_items:
    - libsmbclient
    - samba-client
    - libwbclient
    - cifs-utils
    - glusterfs-fuse

- name: Place samba credentials file for the desktop user
  template:
    src: "{{ path.templates }}/credentials.j2"
    dest: /etc/samba/.credentials
    owner: root
    group: root
    mode: 0640

- name: Ensure directories exist
  ansible.builtin.file:
    path: "/mnt/{{ item.volume }}"
    state: directory
  loop: "{{ gluster_volumes }}"

- name: Add mountpoints to /etc/fstab
  mount:
    name: "/mnt/{{ item.volume }}"
    state: present
    src: "localhost:/{{ item.volume }}"
    fstype: glusterfs
    opts: defaults
  loop: "{{ gluster_volumes }}"

- name: Update gnome3 bookmarks
  copy:
    src: "{{ path.files }}/g3bookmarks.desktop"
    dest: /home/user/.config/gtk-3.0/bookmarks
    owner: user
    group: user
    mode: 0664
