---
- name: Ensure necessary software is installed to allow network access
  package:
    name: "{{item}}"
    state: present
  with_items:
    - libsmbclient
    - samba-client
    - libwbclient
    - cifs-utils
    - glusterfs-fuse

- name: Place samba credentials file for the desktop user
  template:
    src: "{{ path.templates }}/credentials.j2"
    dest: /etc/samba/.credentials
    owner: root
    group: root
    mode: 0640

- name: Ensure directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /server
    - /backups

- name: Add mountpoints to /etc/fstab
  mount:
    name: "{{ item.value.path }}"
    state: present
    src: "{{ item.value.src }}"
    fstype: "{{ item.value.fstype }}"
    opts: "{{ item.value.opts | default('') }}"
  with_dict:
    server:
      path: /server
      src: '//storage-n01/scanner'
      fstype: cifs
      opts: 'credentials=/etc/samba/.credentials,uid=1000,gid=1000'
    backups:
      path: /backups
      src: 'storage-n01:/backups'
      fstype: glusterfs
      opts: defaults

- name: Update gnome3 bookmarks
  copy:
    src: "{{ path.files }}/g3bookmarks.desktop"
    dest: /home/user/.config/gtk-3.0/bookmarks
    owner: user
    group: user
    mode: 0664
