---
- name: Ensure necessary software is installed to allow network access
  package:
    name: "{{item}}"
    state: present
  with_items:
    - libsmbclient
    - samba-client
    - libwbclient
    - cifs-utils
    - glusterfs-fuse

- name: Place samba credentials file for the desktop user
  template:
    src: "{{ templates }}/credentials.j2"
    dest: /etc/samba/.credentials
    owner: root
    group: root
    mode: 0640

- name: Ensure directories exist
  file:
    path: "{{ item }}"
    ensure: directory
    state: present
  with_items:
    - /scanner
    - /backups

- name: Add mountpoints to /etc/fstab
  mount:
    name: "{{ item.path }}"
    state: present
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts | default('') }}"
  with_dict:
    scanner:
      path: /scanner
      src: '//storage-n01/scanner'
      fstype: cifs
      opts: 'credentials=/etc/samba/.credentials,uid=1000,gid=1000'
    backups:
      path: /backups
      src: 'storage-n01:/backups'
      fstype: glusterfs

- name: Update gnome3 bookmarks
  copy:
    src: "{{ files }}/g3bookmarks.desktop"
    dest: /home/temp/.config/gtk-3.0/bookmarks
    owner: temp
    group: temp
    mode: 0664
