---
- ansible.builtin.package:
    state: latest
    name:
    - glusterfs-selinux
    - glusterfs-server

- ansible.builtin.service:
    state: started
    name: glusterd

- gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ groups['gluster'][0] }}"
  retries: 3
  delay: 5
