---
- name: reload firewalld
  ansible.builtin.command: firewall-cmd --reload

- name: sync cobbler
  ansible.builtin.command: cobbler sync

- name: restart cobblerd
  ansible.builtin.service:
    name: cobblerd
    state: restarted

- name: reload systemd
  ansible.builtin.systemd:
    daemon-reload: yes
